coe/app/urls.py
#imports django
from django.urls import path
from django.conf.urls import url
#Import de modulos personales
from . import views as views
from . import app_apis as app_apis
from . import autocomplete


#Definimos paths de la app
app_name = 'app'
urlpatterns = [
    #App
    path('config', app_apis.AppConfig, name='AppConfig'),
    path('registro', app_apis.registro, name='registro'),
    path('foto_perfil', app_apis.foto_perfil, name='foto_perfil'),
    path('encuesta', app_apis.encuesta, name='encuesta'),
    path('start/tracking', app_apis.start_tracking, name='start_tracking'),
    path('tracking', app_apis.tracking, name='tracking'),
    path('salvoconducto', app_apis.pedir_salvoconducto, name='pedir_salvoconducto'),
    path('get/salvoconducto', app_apis.ver_salvoconducto, name='ver_salvoconducto'),
    path('control/salvoconducto', app_apis.control_salvoconducto, name='control_salvoconducto'),
    path('denuncia', app_apis.denuncia_anonima, name='denuncia_anonima'),
    path('get/notificacion', app_apis.notificacion, name='notificacion'),
    #Testing
    path('send/notificacion', views.enviar_notificacion, name='enviar_notificacion'),
    path('save/notificacion', views.guardar_notificacion, name='enviar_notificacion'),
    #Descarga
    path('coe_app', views.download_app, name='download_app'),
    #path('simmov_app', views.download_control, name='download_control'),
    #Autocomplete:
    url(r'^appdata-autocomplete/$', autocomplete.AppDataAutocomplete.as_view(), name='appdata-autocomplete'),
    url(r'^dispositivo-autocomplete/$', autocomplete.DispositivoAutocomplete.as_view(), name='dispositivo-autocomplete'),
]

coe/coe/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path, include

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from django.conf import settings
#Imports Extras
import debug_toolbar

#Path
urlpatterns = [
    path('admin/', admin.site.urls),
    #Admin-User Paths
    url(r'^login/$', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    path('consultas/', include('consultas.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('operadores/', include('operadores.urls')),
    path('actas/', include('actas.urls')),
    path('tareas/', include('tareas.urls')),
    path('inventario/', include('inventario.urls')),
    path('informacion/', include('informacion.urls')),
    path('seguimiento/', include('seguimiento.urls')),
    path('geotracking/', include('geotracking.urls')),
    path('permisos/', include('permisos.urls')),
    path('graficos/', include('graficos.urls')),
    path('documentos/', include('documentos.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('background/', include('background.urls')),
    path('tablero/', include('tablero.urls')),
    #APIS:
    path('api_refs/', include('wservices.urls')),
    path('ide/', include('geotracking.ide_urls')),
    path('covid19/', include('app.urls')),
    #Manejo de Archivos Privados:
    #path('archivos/', include('operadores.file_urls')),#Lo hacemos desde ahi por que depende de permisos
]
#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coe/geotracking/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views as views
from . import autocomplete

#Definimos paths de la app
app_name = 'geotracking'
urlpatterns = [
    #App
    path('', views.menu_geotracking, name='menu_geotracking'),
    #Tracking
    path('ver/<int:individuo_id>', views.ver_tracking, name='ver_tracking'),
    path('procesar/<int:geoposicion_id>', views.procesar_alerta, name='procesar_alerta'),
    path('delete/<int:geoposicion_id>', views.delete_geopos, name='delete_geopos'),
    #Panel GeoOperador
    path('lista/sin_geoperador', views.lista_sin_geoperador, name='lista_sin_geoperador'),
    path('asignar/geoperador/<int:individuo_id>', views.asignar_geoperador, name='asignar_geoperador'),
    path('lista/geoperadores', views.lista_geooperadores, name='lista_geooperadores'),
    path('agregar/geoperador', views.agregar_geoperador, name='agregar_geoperador'),
    path('del/geoperador/<int:geoperador_id>', views.del_geoperador, name='del_geoperador'),
    #Admin
    path('general', views.control_tracking, name='control_tracking'),
    path('lista/trackeados', views.lista_trackeados, name='lista_trackeados'),
    path('lista/alertas', views.lista_alertas, name='lista_alertas'),
    path('lista/procesadas', views.alertas_procesadas, name='alertas_procesadas'),
    path('auditar/asignaciones', views.auditar_asignaciones, name='auditar_asignaciones'),
    path('auditar/asignaciones/<int:geoperador_id>', views.auditar_asignaciones, name='auditar_asignaciones'),
    #Panel
    path('cambiar_base/<int:geoposicion_id>', views.cambiar_base, name='cambiar_base'),
    path('config/<int:individuo_id>', views.config_tracking, name='config_tracking'),
    path('panel/geooperador', views.panel_geoperador, name='panel_geoperador'),
    path('panel/geooperador/<int:geoperador_id>', views.panel_geoperador, name='ver_geopanel'),
    path('agregar/individuo/<int:geoperador_id>', views.agregar_individuo, name='agregar_individuo'),
    path('quitar/individuo/<int:geoperador_id>/<int:individuo_id>', views.quitar_individuo, name='quitar_individuo'),
    #Autocomplete
    url(r'^individuostrackeados-autocomplete/$', autocomplete.IndividuosTrackeadosAutocomplete.as_view(), name='individuostrackeados-autocomplete',),
    url(r'^geoperadores-autocomplete/$', autocomplete.GeOperadoresAutocomplete.as_view(), name='geoperadores-autocomplete',),
    #Wservice
    path('json/<str:num_doc>', views.json_individuo, name='json_individuo'),
]

coe/seguimiento/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views as views
from . import autocomplete
from .views import GisDel

#Definimos paths de la app
app_name = 'seguimiento'
urlpatterns = [
    #Publico:
    path('alta', views.buscar_alta_aislamiento, name='buscar_alta_aislamiento'),
    path('test', views.pedir_test, name='pedir_test'),
    #Menu
    path('', views.menu_seguimiento, name='menu_seguimiento'),
    #Base
    path('lista/seguimientos', views.lista_seguimientos, name='lista_seguimientos'),
    path('ver/<int:individuo_id>', views.ver_seguimiento, name='ver_seguimiento'),
    #Seguimiento
    path('cargar/seguimiento/<int:individuo_id>', views.cargar_seguimiento, name='cargar_seguimiento'),
    path('cargar/seguimiento/<int:individuo_id>/tipo/<str:tipo>', views.cargar_seguimiento, name='cargar_seguimiento'),
    path('mod/seguimiento/<int:individuo_id>/<int:seguimiento_id>', views.cargar_seguimiento, name='mod_seguimiento'),
    path('del/seguimiento/<int:seguimiento_id>', views.del_seguimiento, name='del_seguimiento'),
    path('fin/seguimiento/<int:vigia_id>/<int:individuo_id>', views.fin_seguimiento, name='fin_seguimiento'),
    #Condicion
    path('cargar/condicion/<int:individuo_id>', views.crear_condicion, name='crear_condicion'),
    path('mod/condicion/<int:individuo_id>/<int:condicion_id>', views.crear_condicion, name='mod_condicion'),
    path('del/condicion/<int:condicion_id>', views.del_condicion, name='del_condicion'),
    path('lista/requieren/atencion', views.lista_requiere_atencion, name='lista_requiere_atencion'),
    path('lista/requieren/atencion/atrib/<str:atrib>', views.lista_requiere_atencion, name='lista_requiere_atencion_filtro'),
    path('atender/condiciones/<int:condicion_id>', views.atender_condiciones, name='atender_condiciones'),
    path('lista/atendidos', views.lista_atendidos, name='lista_atendidos'),
    #Lista Para Liberar:
    path('lista/esperando/alta', views.esperando_alta_seguimiento, name='esperando_alta_seguimiento'),
    path('dar/alta/seguimiento/<int:individuo_id>', views.dar_alta_seguimiento, name='dar_alta_seguimiento'),
    path('lista/altas/realizadas', views.altas_realizadas, name='altas_realizadas'),
    path('dar/alta/medica/<int:individuo_id>', views.dar_alta_medica, name='dar_alta_medica'),
    #Administracion
    path('lista/vigias', views.lista_vigias, name='lista_vigias'),
    path('lista/ocupacion', views.lista_ocupacion, name='lista_ocupacion'),
    path('vigia/agregar', views.agregar_vigia, name='agregar_vigia'),
    path('vigia/mod/<int:vigia_id>', views.agregar_vigia, name='mod_vigia'),
    path('vigia/config/<int:vigia_id>', views.configurar_vigia, name='configurar_vigia'),
    path('vigia/del/<int:vigia_id>', views.del_vigia, name='del_vigia'),
    path('lista/sin/vigias', views.lista_sin_vigias, name='lista_sin_vigias'),
    path('vigia/mod/estado/<int:vigia_id>', views.mod_estado_vigia, name='mod_estado_vigia'),
    path('vigia/rellenar/<int:vigia_id>', views.rellenar_vigia, name='rellenar_vigia'),
    #Cazador 360
    path('operativos/situacion', views.situacion_operativos, name='situacion_operativos'),
    path('operativos/lista', views.lista_operativos, name='lista_operativos'),
    path('operativo/crear', views.crear_operativo, name='crear_operativo'),
    path('operativo/mod/<int:operativo_id>', views.crear_operativo, name='mod_operativo'),
    path('operativo/del/<int:operativo_id>', views.del_operativo, name='del_operativo'),
    path('operativo/ver/<int:operativo_id>', views.ver_operativo, name='ver_operativo'),
    path('operativo/agregar/cazador/<int:operativo_id>', views.agregar_cazador, name='agregar_cazador'),
    path('operativo/quitar/cazador/<int:operativo_id>/<int:individuo_id>', views.quitar_cazador, name='quitar_cazador'),
    path('operativo/agregar/testeado/<int:operativo_id>', views.agregar_testeado, name='agregar_testeado'),
    path('operativo/quitar/testeado/<int:operativo_id>/<int:individuo_id>', views.quitar_testeado, name='quitar_testeado'),
    path('operativo/iniciar/<int:operativo_id>', views.iniciar_operativo, name='iniciar_operativo'),
    path('operativo/finalizar/<int:operativo_id>', views.finalizar_operativo, name='finalizar_operativo'),
    #path('operativo/quitar/testeado/<int:operativo_id>/<int:individuo_id>', views.quitar_testeado, name='quitar_testeado'),
    #Otros Listados
    path('test/pedidos', views.ranking_test, name='ranking_test'),
    path('test/esperando', views.esperando_test, name='esperando_test'),
    path('test/realizados', views.test_realizados, name='test_realizados'),
    path('lista/sin_telefono', views.lista_sin_telefono, name='lista_sin_telefono'),
    path('quitar/sintel/<int:individuo_id>', views.quitar_lista_sintel, name='quitar_lista_sintel'),
    path('lista/autodiagnosticos', views.lista_autodiagnosticos, name='lista_autodiagnosticos'),
    path('lista/aislados', views.lista_aislados, name='lista_aislados'),
    #Situacion
    path('situacion/vigilancia', views.situacion_vigilancia, name='situacion_vigilancia'),
    path('reporte/vigilantes', views.reporte_vigilantes, name='reporte_vigilantes'),
    path('seguimientos/vigia/<int:vigia_id>', views.seguimientos_vigia, name='seguimientos_vigia'),
    path('auditar/vigilados', views.auditar_controlados, name='auditar_controlados'),
    path('carentes', views.carentes_seguimiento, name='carentes_seguimiento'),
    #Panel
    path('panel/vigia', views.panel_vigia, name='mi_panel'),
    path('panel/vigia/<int:vigia_id>', views.panel_vigia, name='ver_panel'),
    path('agregar/vigilado/<int:vigia_id>', views.agregar_vigilado, name='agregar_vigilado'),
    path('quitar/vigilado/<int:vigia_id>/<int:individuo_id>', views.quitar_vigilado, name='quitar_vigilado'),
    path('altas/realizadas/<int:vigia_id>', views.altas_cargadas, name='altas_cargadas'),
    path('auditar/vigilados/<int:vigia_id>', views.auditar_controlados, name='auditar_controlados'),
    #Gis
    path('gis/lista', views.gis_list, name="gis_list"),
    path('gis/cargar', views.cargar_gis, name="cargar_gis"),
    path('gis/mod/datos/<int:datosgis_id>', views.cargar_gis, name="mod_gis"),
    path('gis/delete/datos/<int:pk>', GisDel.as_view(), name='gis_del'),
    #Seguimiento PLP
    path('muestras/bioq/list', views.muestra_list_bioq, name="muestra_list_bioq"),
    path('muestras/comp/list', views.muestra_list_comp, name="muestra_list_comp"),
    path('muestras/panel/list', views.muestra_list_panel, name="muestra_list_panel"),
    path('muestras/edit/bioq/<int:muestra_id>', views.edit_bioq, name="edit_bioq"),
    path('muestras/buscar/persona', views.buscar_persona_muestra, name="buscar_persona_muestra"),
    path('muestras/existe/<int:individuo_id>/<str:num_doc>/', views.cargar_muestra, name='existe_plp'),
    path('muestras/cargar/<str:num_doc>/', views.cargar_muestra, name='cargar_muestra'),
    path('muestras/editar/panel/<int:muestra_id>', views.editar_muestra, name="editar_muestra"),
    path('muestras/editar/panel/<int:muestra_id>', views.cargar_muestra, name="editar_plp"),
    path('muestras/panel_editar/<int:muestra_id>', views.edit_panel, name="editar_panel_plp"),
    path('muestras/upload/masivo', views.upload_muestra, name="upload_muestra"),
    path('muestras/delete/datos/<int:pk>', views.MuestraDel.as_view(), name='muestra_del'),
    #Autocomplete
    url(r'^individuosvigilados-autocomplete/$', autocomplete.IndividuosVigiladosAutocomplete.as_view(), name='individuosvigilados-autocomplete',),
    url(r'^vigias-autocomplete/$', autocomplete.VigiasAutocomplete.as_view(), name='vigias-autocomplete',),
]

coe/geotracking/forms.py
#Imports Django
from django import forms
#Imports extra
from dal import autocomplete
#Imports del proyecto
from informacion.models import Individuo
#Imports de la app
from .models import GeOperador

#Definimos nuestros forms aqui:
class ConfigGeoForm(forms.Form):
    intervalo = forms.IntegerField(label="Intervalo entre Trackings")
    distancia_alerta = forms.IntegerField(label="Distancia de Alerta")
    distancia_critica = forms.IntegerField(label="Distancia Critica")

class NuevoGeoOperador(forms.ModelForm):
    class Meta:
        model = GeOperador
        fields= '__all__'
        exclude = ('controlados', )
        widgets = {
            'operador': autocomplete.ModelSelect2(url='operadores:operadores-autocomplete'),
        }

class NuevoIndividuo(forms.Form):
    individuo = forms.ModelChoiceField(
        queryset= Individuo.objects.all(),
        required= True,
        widget= autocomplete.ModelSelect2(url='geotracking:individuostrackeados-autocomplete'),
    )

class AsignarGeOperador(forms.Form):
    geoperador = forms.ModelChoiceField(
        queryset=GeOperador.objects.all(),
        required=True,
        widget= autocomplete.ModelSelect2(url='geotracking:geoperadores-autocomplete'),
    )

coe/geotracking/templates/control_tracking.html
{% extends 'base_informacion.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2><b>Control del Sistema de Trackeo</b></h2>
        </div>
        <div class="row">
            <div class="col-md-12">
                {% include 'mapa_general.html' %}
            </div>
            <hr>
            <div class="col-md-12">
                <h3>Ultimas Alertas:</h3>
                <table class="listado" id="table">
                    <thead>
                        <tr>
                            <th>Tipo de Alerta</th>
                            <th>Individuo</th>
                            <th>Situacion</th>
                            <th>Domicilio</th>
                            <th>Telefono</th>
                            <th>Fecha y Hora</th>
                            <th>Distancia</th>
                            <th>Ver Detalle</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for alerta in alertas %}
                            {% include 'linea_alerta.html' %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

coe/geotracking/templates/linea_alerta.html
{% load static %}
{% load geotracking %}

{% block content %}
    <tr id="{{alerta.id}}" class="{% ct_color_alerta alerta.alerta %}">
        <td><b>{{alerta.get_alerta_display}}</b></td>
        <td>{{alerta.individuo.apellidos}}, {{alerta.individuo.nombres}}</td>
        <td>{{alerta.individuo.situacion_actual}}</td>
        <td>{{alerta.individuo.domicilio_actual}}</td>
        <td>{{alerta.individuo.telefono}}</td>
        <td>{{alerta.fecha|date:"d/m H:i"}}</td>
        <td>{{alerta.distancia}}</td>
        <td>
            <a href="{% url 'geotracking:ver_tracking' individuo_id=alerta.individuo.id %}" target="_blank">
                <img class="icons" src="{% static '/img/icons/tracking.png' %}">
            </a>
            <a href="{% url 'informacion:ver_individuo' individuo_id=alerta.individuo.id %}" target="_blank">
                <img class="icons" src="{% static '/img/icons/lupa.png' %}">
            </a>
            <a href="{% url 'geotracking:procesar_alerta' geoposicion_id=alerta.id %}" target="_blank">
                <img class="icons" src="{% static '/img/icons/operador.png' %}">
            </a>
        </td>
    </tr>
{% endblock %}

coe/geotracking/templates/lista_geoperadores.html
{% extends 'base_informacion.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2><b>Lista de Controladores</b></h2>
            <a class="botoncito" href="{% url 'geotracking:agregar_geoperador' %}">
                Habilitar nuevo GeOperador
                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
            </a>
            <div class="col-md-12">
                <table class="listado" id="table">
                    <thead>
                        <tr>
                            <th>Operador</th>
                            <th>Telefono</th>
                            <th>Ultimo Ingreso</th>
                            <th>Cantidad Controlados</th>
                            <th>Alertas Activas</th>
                            <th>Ver Detalle</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for geoperador in geoperadores %}
                            <tr>
                                <td>{{geoperador}}</td>
                                <td>{{geoperador.operador.telefono}}</td>
                                <td>{{geoperador.operador.usuario.last_login}}</td>
                                <td>{{geoperador.cant_controlados}}</td>
                                <td>{{geoperador.alertas_activas}}</td>
                                <td>
                                    <a href="{% url 'geotracking:ver_geopanel' geoperador_id=geoperador.id %}" target="_blank">
                                        <img class="icons" src="/static/img/icons/control_panel.png" alt="Panel de Control">
                                    </a>
                                    <a href="{% url 'geotracking:auditar_asignaciones' geoperador_id=geoperador.id %}" target="_blank">
                                        <img class="icons" src="{% static '/img/icons/history.png' %}">
                                    </a>
                                    <a href="{% url 'geotracking:del_geoperador' geoperador_id=geoperador.id %}">
                                        <img class="icons" src="{% static '/img/icons/delete.png' %}">
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

coe/geotracking/templates/lista_trackeados.html
{% extends 'base_informacion.html' %}

{% load static %}
{% load geotracking %}

{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2>Individuos Registrados</h2>
        </div>
        <div class="row">
        <div class="col-md-12">
            <table class="listado" id="table">
                <thead>
                    <tr>
                        <th>Documento</th>
                        <th>Individuo</th>
                        <th>Fecha de Nacimiento</th>
                        <th>Ubicacion Actual</th>
                        <th>Situacion</th>
                        <th>Ultima Posicion Enviada</th>
                        <th>Ultima Alerta</th>
                        <th>Operadores</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for individuo in individuos %}
                        {% with individuo.ultima_alerta as ultima_alerta %}
                            <tr class="{% ct_color_alerta ultima_alerta.alerta %}">
                                <td>{{individuo.get_tipo_doc_display}} {{individuo.num_doc}}</td>
                                <td>{{individuo.apellidos}}, {{individuo.nombres}}</td>
                                <td>{{individuo.fecha_nacimiento}}</td>
                                <td>{{individuo.domicilio_actual}}</td>
                                <td>{{individuo.situacion_actual}}</td>
                                <td>
                                    {% with individuo.geoposicion as last_posicion %}
                                        {{last_posicion.fecha|date:"d/m H:i"}}
                                    {% endwith %}
                                </td>
                                <td>{{ultima_alerta.fecha|date:"d/m H:i"}}: {{ultima_alerta.get_alerta_display}}</td>
                                <td>
                                    {% for geoperador in individuo.geoperadores.all %}
                                        <a class="nolink" href="{% url 'geotracking:ver_geopanel' geoperador_id=geoperador.id %}">{{geoperador}}</a><br>
                                    {% endfor %}
                                </td>
                                <td>
                                    <a href="{% url 'geotracking:ver_tracking' individuo_id=individuo.id %}" target="_blank">
                                        <img class="icons" src="{% static '/img/icons/tracking.png' %}">
                                    </a>
                                    <a href="{% url 'geotracking:config_tracking' individuo_id=individuo.id %}" target="_blank">
                                        <img class="icons" src="{% static '/img/icons/config.png' %}">
                                    </a>
                                    <a href="{% url 'informacion:ver_individuo' individuo_id=individuo.id %}" target="_blank">
                                        <img class="icons" src="{% static '/img/icons/lupa.png' %}">
                                    </a>
                                    <a href="{% url 'geotracking:asignar_geoperador' individuo_id=individuo.id %}">
                                        <img class="icons" src="{% static '/img/icons/detective.svg' %}" alt="Asignar Trackeador">
                                    </a>
                                </td>
                            </tr>
                        {% endwith %}
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

coe/geotracking/templates/menu_geotracking.html
{% extends 'base_informacion.html' %}

{% load seguridad_tags%}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu GeoTracking:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">
                            {% if perms.operadores.geotracking %}
                                {% if es_geoperador %}
                                    <li><a href="{% url 'geotracking:panel_geoperador' %}">Ver Mi Panel de Control</a></li>
                                    <hr>
                                {% endif %}
                                {% if perms.operadores.geotracking_admin %}
                                    <li><a href="{% url 'geotracking:lista_geooperadores' %}">Listado de GeOperadores Habilitados</a></li>
                                    <hr>
                                    <li><a href="{% url 'geotracking:auditar_asignaciones' %}">Auditar Asignaciones</a></li>
                                    <li><a href="{% url 'geotracking:control_tracking' %}">Sistema de Control GeoPosicional</a></li>
                                    <li><a href="{% url 'geotracking:lista_sin_geoperador' %}">Listado de Individuos Sin GeOperador</a></li>
                                    <li><a href="{% url 'geotracking:lista_alertas' %}">Listado de Alertas Activas</a></li>
                                    <li><a href="{% url 'geotracking:lista_trackeados' %}">Listado de Individuos Bajo Seguimiento</a></li>
                                    <hr>
                                    <li><a href="{% url 'geotracking:alertas_procesadas' %}">Listado de Alertas Procesadas</a></li>
                                {% endif %}
                            {% endif %}

                            {% if request.user.is_superuser %}
                                <h3>Uso Bajo Supervision:</h3>
                                <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        {% include 'info_user.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

coe/geotracking/templates/panel_geoperador.html
{% extends 'base_informacion.html' %}
{% load static %}
{% block content %}
    <div class="beneficiario container">
        <div class="row">
            <h2><b>Panel de {{geoperador}}</b></h2>
            <div class="col-md-8">
                <h3>Alertas Activas ({{geoperador.alertas_activas}})</h3>
                <table class="listado" id="table">
                    <thead>
                        <tr>
                            <th>Tipo de Alerta</th>
                            <th>Individuo</th>
                            <th>Situacion</th>
                            <th>Domicilio</th>
                            <th>Telefono</th>
                            <th>Fecha y Hora</th>
                            <th>Distancia</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for alerta in alertas %}
                            {% include 'linea_alerta.html' %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-md-4">
                <h3>
                    Individuos Controlados ({{geoperador.cantidad_controlados}})
                    <a href="{% url 'geotracking:auditar_asignaciones' geoperador_id=geoperador.id %}" target="_blank">
                        <img class="icons" src="{% static '/img/icons/history.png' %}">
                    </a>
                </h3>
                {% if perms.operadores.geotracking_admin %}
                    <a class="botoncito" href="{% url 'geotracking:agregar_individuo' geoperador_id=geoperador.id %}">
                        Asignar Nuevo Individuo
                        <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo">
                    </a>
                {% endif %}
                <table class="listado">
                    <thead>
                        <tr>
                            <th>Individuo</th>
                            <th>Telefono</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for individuo in geoperador.controlados.all %}
                            <tr>
                                <td>{{individuo}}</td>
                                <td>{{individuo.telefono}}</td>
                                <td>
                                    <a class="nolink"  href="{% url 'geotracking:ver_tracking' individuo_id=individuo.id %}" target="_blank">
                                        <img class="icons" src="{% static '/img/icons/tracking.png' %}">
                                    </a>
                                    {% if perms.operadores.individuos %}
                                        <a class="nolink"  href="{% url 'informacion:ver_individuo' individuo_id=individuo.id %}" target="_blank">
                                            <img class="icons" src="{% static '/img/icons/lupa.png' %}">
                                        </a>
                                    {% endif %}
                                    {% if perms.operadores.geotracking_admin %}
                                        <a class="nolink"  href="{% url 'geotracking:quitar_individuo' geoperador_id=geoperador.id individuo_id=individuo.id %}">
                                            <img class="icons" src="{% static '/img/icons/delete.png' %}">
                                        </a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
{% endblock %}