coe/app/urls.py
#imports django
from django.urls import path
from django.conf.urls import url
#Import de modulos personales
from . import views as views
from . import app_apis as app_apis
from . import autocomplete


#Definimos paths de la app
app_name = 'app'
urlpatterns = [
    #App
    path('config', app_apis.AppConfig, name='AppConfig'),
    path('registro', app_apis.registro, name='registro'),
    path('foto_perfil', app_apis.foto_perfil, name='foto_perfil'),
    path('encuesta', app_apis.encuesta, name='encuesta'),
    path('start/tracking', app_apis.start_tracking, name='start_tracking'),
    path('tracking', app_apis.tracking, name='tracking'),
    path('salvoconducto', app_apis.pedir_salvoconducto, name='pedir_salvoconducto'),
    path('get/salvoconducto', app_apis.ver_salvoconducto, name='ver_salvoconducto'),
    path('control/salvoconducto', app_apis.control_salvoconducto, name='control_salvoconducto'),
    path('denuncia', app_apis.denuncia_anonima, name='denuncia_anonima'),
    path('get/notificacion', app_apis.notificacion, name='notificacion'),
    #Testing
    path('send/notificacion', views.enviar_notificacion, name='enviar_notificacion'),
    path('save/notificacion', views.guardar_notificacion, name='enviar_notificacion'),
    #Descarga
    path('coe_app', views.download_app, name='download_app'),
    #path('simmov_app', views.download_control, name='download_control'),
    #Autocomplete:
    url(r'^appdata-autocomplete/$', autocomplete.AppDataAutocomplete.as_view(), name='appdata-autocomplete'),
    url(r'^dispositivo-autocomplete/$', autocomplete.DispositivoAutocomplete.as_view(), name='dispositivo-autocomplete'),
]

coe/coe/urls.py
#Imports de Django
from django.conf.urls import url
from django.urls import path, include

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from django.conf import settings
#Imports Extras
import debug_toolbar

#Path
urlpatterns = [
    path('admin/', admin.site.urls),
    #Admin-User Paths
    url(r'^login/$', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    #Extras
    url(r'^tinymce/', include('tinymce.urls')),
    #Debug:
    path('__debug__/', include(debug_toolbar.urls)),
    #Apps:
    path('', include('core.urls')),
    path('consultas/', include('consultas.urls')),
    path('georef/', include('georef.urls')),
    path('noticias/', include('noticias.urls')),
    path('operadores/', include('operadores.urls')),
    path('actas/', include('actas.urls')),
    path('tareas/', include('tareas.urls')),
    path('inventario/', include('inventario.urls')),
    path('informacion/', include('informacion.urls')),
    path('seguimiento/', include('seguimiento.urls')),
    path('geotracking/', include('geotracking.urls')),
    path('permisos/', include('permisos.urls')),
    path('graficos/', include('graficos.urls')),
    path('documentos/', include('documentos.urls')),
    path('inscripciones/', include('inscripciones.urls')),
    path('background/', include('background.urls')),
    path('tablero/', include('tablero.urls')),
    #APIS:
    path('api_refs/', include('wservices.urls')),
    path('ide/', include('geotracking.ide_urls')),
    path('covid19/', include('app.urls')),
    #Manejo de Archivos Privados:
    #path('archivos/', include('operadores.file_urls')),#Lo hacemos desde ahi por que depende de permisos
]
#Agregamos destinos de Archivos Estaticos
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coe/operadores/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views
from . import autocomplete

app_name = 'operadores'
urlpatterns = [
    path('', views.menu, name='menu'),
    #ABM SubComites
    path('listar/subco', views.listar_subcomites, name='listar_subcomites'),
    path('ver/subco/<int:subco_id>', views.ver_subcomite, name='ver_subcomite'),
    path('crear/subco', views.crear_subcomite, name='crear_subcomite'),
    path('mod/subco/<int:subco_id>', views.crear_subcomite, name='mod_subcomite'),
    #ABM Operadores
    path('listar/op', views.listar_operadores, name='listar_operadores'),
    path('crear/op', views.crear_operador, name='crear_operador'),
    path('modificar/op/<int:operador_id>', views.mod_operador, name='modificar_usuario'),
    path('check/individuo/<int:operador_id>', views.check_individuo, name='check_individuo'),
    path('chpass/op/<int:operador_id>', views.cambiar_password, name='cambiar_password'),
    path('desactivar/op/<int:operador_id>', views.desactivar_usuario, name='desactivar_usuario'),
    path('activar/op/<int:operador_id>', views.activar_usuario, name='activar_usuario'),
    path('credencial/op/<int:operador_id>', views.ver_credencial, name='ver_credencial'),
    path('imprimir', views.imprimir_tarjetas, name='imprimir_tarjetas'),
    #Auditoria
    path('auditoria', views.auditoria, name='auditoria'),
    path('auditoria/<int:user_id>', views.auditoria, name='auditoria_propia'),
    path('auditar/obj/<int:content_id>/<int:object_id>', views.auditar_cambios, name='auditar_cambios'),
    path('asistencia/<int:operador_id>', views.asistencia, name='asistencia'),
    #Asistencia
    path('presentes', views.listado_presentes, name='listado_presentes'),
    path('checkin', views.checkin, name='checkin'),
    path('ingreso/<int:operador_id>', views.ingreso, name='ingreso'),
    path('checkout/<int:operador_id>', views.checkout, name='checkout'),
    path('asistencia', views.registro_asistencia, name='registro_asistencia'),
    #Reportes
    path('csv/', views.csv_operadores, name='csv_operadores'),
    #Autocomplete
    url(r'^operadores-autocomplete/$', autocomplete.OperadoresAutocomplete.as_view(), name='operadores-autocomplete',),
    url(r'^subcomite-autocomplete/$', autocomplete.SubComiteAutocomplete.as_view(), name='subcomite-autocomplete',),
]

coe/tareas/urls.py
#imports django
from django.conf.urls import url
from django.urls import path
#Import de modulos personales
from . import views
from . import autocomplete

#Definimos paths de la app
app_name = 'tareas'
urlpatterns = [
    path('', views.menu, name='menu'),
    #Basicas:
    path('lista', views.lista_tareas, name='lista_tareas'),
    path('lista/terminadas', views.lista_terminadas, name='lista_terminadas'),
    path('ver/<int:tarea_id>', views.ver_tarea, name='ver_tarea'),
    path('crear', views.crear_tarea, name='crear_tarea'),
    path('mod/<int:tarea_id>', views.crear_tarea, name='mod_tarea'),
    path('cancelar/<int:tarea_id>', views.cancelar_tarea, name='cancelar_tarea'),

    path('agregar/responsable/<int:tarea_id>', views.agregar_responsable, name='agregar_responsable'),
    path('eliminar/responsable/<int:responsable_id>', views.eliminar_responsable, name='eliminar_responsable'),
    path('agregar/evento/<int:tarea_id>', views.agregar_evento, name='agregar_evento'),
    path('eliminar/evento/<int:evento_id>', views.eliminar_evento, name='eliminar_evento'),
    #Autocomplete
    url(r'^tareas-autocomplete/$', autocomplete.TareasAutocomplete.as_view(), name='tareas-autocomplete',),
]

coe/app/models.py
#Imports de django
from django.db import models
from django.utils import timezone
#Imports Extras
from fcm_django.models import FCMDevice
#Imports del proyecto
from informacion.models import Individuo
#Imports de la app
from .choices import TIPO_TRIAJE
from .choices import TIPO_ACCION_NOTIFICACION

# Create your models here.
class AppData(models.Model):
    individuo = models.OneToOneField(Individuo, on_delete=models.CASCADE, related_name="appdata")
    telefono = models.CharField('Telefono', max_length=50, default='+549388')
    email = models.EmailField('Correo Electronico', null=True, blank=True)#Enviar mails
    estado = models.CharField('Estado', choices=TIPO_TRIAJE, max_length=1, default='V')
    device = models.OneToOneField(FCMDevice, on_delete=models.SET_NULL, null=True, blank=True, related_name="appdata")
    fecha = models.DateTimeField('Fecha del Registro', default=timezone.now)
    #GeoTracking
    intervalo = models.IntegerField("Intervalo entre Trackings",default=10)#Minutos
    distancia_alerta = models.IntegerField("Distancia de Alerta", default=50)#Mts
    distancia_critica = models.IntegerField("Distancia Critica", default=100)#Mts
    def __str__(self):
        return str(self.individuo) + self.get_estado_display()

class AppNotificacion(models.Model):
    appdata = models.OneToOneField(AppData, on_delete=models.CASCADE, related_name="notificacion")
    titulo = models.CharField('titulo', max_length=100, default='', blank=False)
    mensaje = models.CharField('mensaje', max_length=200, default='', blank=False)
    accion = models.CharField('accion', choices=TIPO_ACCION_NOTIFICACION, max_length=2, default='SM')
    fecha = models.DateTimeField('Fecha del Registro', default=timezone.now)

coe/operadores/models.py
#Imports de python
import qrcode
#Realizamos imports de Django
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
#Imports de paquetes extras
from auditlog.registry import auditlog
from tinymce.models import HTMLField
#Imports del proyecto:
from coe.settings import MEDIA_ROOT, LOADDATA
from coe.constantes import NOIMAGE
from core.choices import TIPO_DOCUMENTOS
from informacion.models import Individuo
#improts de la app
from .choices import TIPO_EVENTO, NIVELES_SEGURIDAD

# Create your models here.
class SubComite(models.Model):
    nombre = models.CharField('Nombre', max_length=100, unique=True)
    descripcion = HTMLField(null=True)
    activo = models.BooleanField(default=True)
    class Meta:
        verbose_name = 'Modulo'
        verbose_name_plural = 'Modulos'
        ordering = ['nombre', ]
    def __str__(self):
        return self.nombre
    def as_dict(self):
        return {
            'id': self.id,
            'nombre': self.nombre,
            'descripcion': self.descripcion,
            'activo': self.activo,
        }
    def cant_miembros(self):
        return self.operadores.count()
    def cant_tareas_terminadas(self):
        cant = 0
        for tarea in self.tareas.all():
            evento = [t for t in tarea.eventos.all()][-1]
            if evento.accion == 'E':
                    cant+=1
        return cant
    def cant_tareas_pendientes(self):
        cant = 0
        for tarea in self.tareas.all():
            evento = [t for t in tarea.eventos.all()][-1]
            if not evento.accion == 'E':
                    cant+=1
        return cant
    def tareas_pendientes(self):
        return self.tareas.exclude(eventos__accion="E")

class Operador(models.Model):
    subcomite = models.ForeignKey(SubComite, on_delete=models.SET_NULL, null=True, related_name="operadores")
    nivel_acceso = models.CharField("Acceso de Seguridad", max_length=1, choices=NIVELES_SEGURIDAD, default='B')
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="operadores")
    tipo_doc = models.IntegerField(choices=TIPO_DOCUMENTOS, default=2)
    num_doc = models.CharField('Numero de Documento', unique=True, max_length=100)
    individuo = models.OneToOneField(Individuo, on_delete=models.SET_NULL, null=True, blank=True, related_name="operador")
    apellidos = models.CharField('Apellidos', max_length=100)
    nombres  = models.CharField('Nombres', max_length=100)
    email = models.EmailField('Correo Electronico')
    telefono = models.CharField('Telefono', max_length=20, default='+549388')
    fotografia = models.FileField('Fotografia', upload_to='operadores/', null=True, blank=True)
    qrpath = models.CharField('qrpath', max_length=100, null=True, blank=True)
    class Meta:
        verbose_name_plural = 'Operadores'
        ordering = ['apellidos', 'nombres']
        permissions = (
            #Consultas
            ("telefonistas", "Acceso a CallCenter."),
            ("admin_telefonistas", "Administrador de CallCenter."),
            #Operadores:
            ("operadores", "Crear/Modificar Operadores"),
            ("auditar_operadores", "Auditar Operadores"),
            ("admin_operadores", "Administrar Usuarios."),
            #Georef
            ("menu_georef", "Informacion Geografica/Ubicaciones"),
            #Inventario
            ("menu_inventario", "Menu Inventario"),
            #Tareas:
            ("menu_tareas", "Menu de Tareas"),
            #Informacion:
            ("menu_informacion", "Menu de Informacion"),
            ("archivos", "Crear Archivos."),
            ("vehiculos", "Informacion de Vehiculo."),
            ("individuos", "Informacion de Individuos."),
            ("admin_informacion", "Se puede modificar Informacion compleja de Individuos."),
            ("epidemiologia", "Acceso a Informacion Epidemiologica Confidencial"),
            #Seguimiento:
            ("seguimiento", "Monitor Seguimiento de Individuos."),
            ("seguimiento_admin", "Administrar Sistema de Seguimiento."),
            ("operativos", "Operativos de Test Masivos."),
            ("carga_gis", "Carga datos GeoEpidemilógicos"),
            #Muestras:
            ("bioq_plp", "Carga de Bioquimicos PLP"),
            ("carga_plp", "Carga Completa PLP"),
            ("panel_plp", "Panel PLP"), 
            #GeoTracking
            ("geotracking", "Monitore Tracking de Individuos."),
            ("geotracking_admin", "Administrador Sistema de GeTracking."),
            #Permisos:
            ("permisos", "Permisos de Circulacion."),
            ("fronteras", "Personal de Control en Fronteras."),
            #Graficos:
            ("menu_graficos", "Administrar Graficos"),
            #Actas:
            ("menu_actas", "Menu de Actas"),
            #Documentos
            ("menu_documentos", "Menu de Documentos"),
            ("documentos", "Puede Administrar Documentos"),
            #Inscripciones:
            ("menu_inscripciones", "Menu de Inscripciones"),
            #Reportes
            ("reportes", "Reportes del sistema"),
            #Tablero
            ("tablero_jerarquico", "Tablero General del Sistema"),
            #Wservices
            ("wservices", "WebServices del Sistema"),
            #Extras:
            ("tablero_comando", "Tableros de Informacion Jerarquica"),
        )
    def __str__(self):
        return self.apellidos + ', ' + self.nombres
    def as_dict(self):
        return {
            'id': self.id,
            'subcomite': str(self.subcomite),
            'usuario': str(self.usuario),
            'tipo_doc': self.tipo_doc,
            'num_doc': self.num_doc,
            'apellidos': self.apellidos,
            'nombres': self.nombres,
            'email': self.email,
            'telefono': self.telefono,
            'fotografia': str(self.fotografia),
            'qrpath': str(self.qrpath),
        }
    def get_foto(self):
        if self.fotografia:
            return self.fotografia.url
        else:
            return NOIMAGE
    def get_qrimage(self):
        if self.qrpath:
            return self.qrpath
        else:
            path = MEDIA_ROOT + '/operadores/qrcode-'+ str(self.num_doc)
            img = qrcode.make(str(self.num_doc))
            img.save(path)
            relative_path = '/archivos/operadores/qrcode-'+ str(self.num_doc)
            self.qrpath = relative_path
            self.save()
            return self.qrpath
    def tareas_pendientes(self):
        return [r.tarea for r in self.responsables.all().exclude(tarea__eventos__accion='E')]
    def es_medico(self):
        try:
            if not self.individuo:
                self.individuo = Individuo.objects.get(num_doc=self.num_doc)
                self.save()
            return self.individuo.atributos.filter(tipo='PM').last()
        except:
            return False

class EventoOperador(models.Model):
    operador = models.ForeignKey(Operador, on_delete=models.CASCADE, null=True, blank=True, related_name="asistencia")
    tipo = models.CharField('Tipo de Evento', max_length=1, choices=TIPO_EVENTO, default='I')
    fecha = models.DateTimeField('Fecha', default=timezone.now)
    def __str__(self):
        return str(self.operador) + ': ' + self.get_tipo_display() + ' - ' + str(self.fecha)
    def as_dict(self):
        return {
            'id': self.id,
            'operador_id': self.operador.id,
            'operador': str(self.operador),
            'tipo': self.get_tipo_display(),
            'fecha': str(self.fecha),
        }

if not LOADDATA:
    #Auditoria
    auditlog.register(SubComite)
    auditlog.register(Operador)
    auditlog.register(User)

coe/operadores/templates/ingreso_operador.html
{% extends 'base_operadores.html' %}

{% load adminusers_tags %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <div class="col-sm-7 tarjeta color-{{operador.nivel_acceso}}">
                        <div class="col-sm-8">
                            <h3 class="tipo">COMITE OPERATIVO DE EMERGENCIA</h3>
                            <hr>
                            <div class="informacion">
                                <p class="nums"><b>N° Documento:</b> {{operador.num_doc}}</p>
                                <p><b>Nombre y Apellido:</b></p>
                                <p class="tab">{{operador.usuario.last_name}}, {{operador.usuario.first_name}}</p>
                                <p><b>Subcomite:</b></p>
                                <p class="tab">{{operador.subcomite}}</p>
                                <p><b>Nivel de Acceso:</b></p>
                                <p class="nums">{{operador.get_nivel_acceso_display}}</p>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <div class="row recuadrofoto">
                                <img class="fotos" src="{{operador.get_foto}}">
                            </div>
                            <div class="row">
                                <img class="fotos" src="{{operador.get_qrimage}}">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <ul class="menu_botones">
                            {% if perms.operadores.auditar_operadores %}
                                <li><a href="{% url 'operadores:checkin'  %}">Ingresar Otro Operador</a></li>
                                <li><a href="{% url 'operadores:listado_presentes'  %}">Listado de Operadores Presentes</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}

coe/operadores/templates/lista_operadores.html
{% extends 'base_operadores.html' %}

{% load static %}
{% load adminusers_tags %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Listado de Usuarios: <b>{{app_name}}</b></h1>
                    <p style="float:right;">
                        {% if perms.operadores.operadores %}
                            <a href="{% url 'operadores:crear_operador' %}">
                                Crear Operador
                                <img class="icons" src="/static/admin/img/icon-addlink.svg" alt="Crear Nuevo Usuario">
                            </a>
                        {% endif %}
                    </p>
                </div> 
                <div class="row"> 
                    <div class="col-md-12">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th>Num Documento</th>
                                    <th>Operador</th>
                                    <th>Grupo</th>
                                    <th>Nivel Autorizacion</th>
                                    <th>Telefono</th>
                                    <th>Email</th>
                                    <th>Estado</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for operador in operadores %}
                                    <tr class="fila_usuario">
                                        
                                        <td>{{operador.usuario.username}}</td>
                                        <td>{{operador.num_doc}}</td>
                                        <td>
                                            {{operador.apellidos}}, {{operador.nombres}}
                                            {% if operador.individuo %}
                                                <a href="{% url 'informacion:ver_individuo' individuo_id=operador.individuo.id %}" target="_blank">
                                                    <img class="icons" src="/static/img/icons/check.png" alt="Ver">
                                                </a>
                                            {% else %}
                                                <a href="{% url 'operadores:check_individuo' operador_id=operador.id %}" target="_blank">
                                                    <img class="icons" src="{% static '/img/icons/reload.png' %}" alt="Modificar">
                                                </a>
                                            {% endif %}
                                        </td>
                                        <td>{{operador.subcomite}}</td>
                                        <td>{{operador.get_nivel_acceso_display}}</td>
                                        <td>{{operador.telefono}}</td>
                                        <td>{{operador.email}}</td>
                                        <td><!-- Icono de Activo -->
                                            {% if operador.usuario.is_active %}
                                                <b style="color:green;">Activo</b>
                                            {% else %}
                                                <b style="color:red;">Inactivo</b>
                                            {% endif %}
                                        </td>
                                        <td><!-- Acciones -->
                                            <a class="nolink" href="{% url 'operadores:ver_credencial' operador_id=operador.id %}">
                                                <img class="icons" src="/static/img/icons/access_card.png" alt="Ver Tarjeta">
                                            </a>
                                            <a class="nolink" href="{% url 'operadores:modificar_usuario'  operador_id=operador.id %}">
                                                <img class="icons" src="/static/admin/img/icon-changelink.svg" alt="Modificar">
                                            </a>
                                            {% if operador.usuario %}
                                                <a class="nolink" href="{% url 'operadores:cambiar_password' operador_id=operador.id %}">
                                                    <img class="icons" src="/static/img/icons/changepassword.png" alt="Cambiar contraseña">
                                                </a>
                                                {% if operador.usuario.is_active %}
                                                    <a class="nolink" href="{% url 'operadores:desactivar_usuario' operador_id=operador.id %}">
                                                        <img class="icons" src="/static/admin/img/icon-deletelink.svg" alt="Desactivar">
                                                    </a>
                                                {% else %}
                                                    <a class="nolink" href="{% url 'operadores:activar_usuario' operador_id=operador.id %}">
                                                        <img class="icons" src="/static/img/icons/check.png" alt="Activar">
                                                    </a>
                                                {% endif %}
                                                {% if perms.operadores.auditar_operadores %}
                                                    <a href="{% url 'operadores:auditoria_propia' user_id=operador.usuario.id %}">
                                                        <img class="icons" src="/static/img/icons/audit.png" alt="Auditoria">
                                                    </a>
                                                {% endif %}
                                            {% endif %}
                                            <a href="{% url 'operadores:asistencia' operador_id=operador.id %}">
                                                <img class="icons" src="/static/img/icons/calendar.png" alt="Asistencia">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   

coe/operadores/templates/listar_presentes.html
{% extends 'base_operadores.html' %}

{% load adminusers_tags %}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">
                    <h1>Listado de Operadores:</h1>
                </div>
                <div class="row">
                    <div class="col-md-8">
                        <table class="listado" id="table">
                            <thead>
                                <tr>
                                    <th>Ingreso</th>
                                    <th>Documento</th>
                                    <th>Operador</th>
                                    <th>Grupo</th>
                                    <th>Nivel de Acceso</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for evento in presentes %}
                                    <tr>
                                        <td>{{evento.fecha|time}}</td>
                                        <td>{{evento.operador.num_doc}}</td>
                                        <td>{{evento.operador.apellidos}}, {{evento.operador.nombres}}</td>
                                        <td>{{evento.operador.subcomite}}</td>
                                        <td>{{evento.operador.get_nivel_acceso_display}}</td>
                                        <td>
                                            <a class="nolink" href="{% url 'operadores:ver_credencial' operador_id=evento.operador.id %}">
                                                <img class="icons" src="/static/img/icons/access_card.png" alt="Ver Tarjeta">
                                            </a>
                                            <a class="nolink" href="{% url 'operadores:checkout' operador_id=evento.operador.id %}">
                                                <img class="icons" src="/static/img/icons/logout.png" alt="Marcar Egreso">
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-4">
                        <ul class="menu_botones">
                            {% if perms.operadores.auditar_operadores %}
                                <li><a href="{% url 'operadores:checkin'  %}">Ingreso Operador</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}   

coe/operadores/templates/menu_operadores.html
{% extends 'base_operadores.html' %}

{% load seguridad_tags%}

{% block content %}
    <section class="resumen">
        <section class="informacion_basica">
            <div class="container">
                <div class="row">        
                    <h1>Menu Operadores:</h1>
                    <div class="col-md-8">
                        <ul class="menu_botones">

                            {% if perms.operadores.operadores %}
                                <hr>
                                <li><a href="{% url 'operadores:crear_operador'  %}">Crear Operador</a></li>
                                <li><a href="{% url 'operadores:listar_operadores'  %}">Ver Listado de Operadores</a></li>
                                <li><a href="{% url 'operadores:imprimir_tarjetas'  %}">Imprimir Credenciales</a></li>
                            {% endif %}

                            {% if perms.operadores.auditar_operadores %}
                                <hr>
                                <li><a href="{% url 'operadores:checkin'  %}">Ingreso Operador</a></li>
                                <li><a href="{% url 'operadores:listado_presentes'  %}">Listado de Presentes</a></li>
                                <li><a href="{% url 'operadores:registro_asistencia'  %}">Registro de Asistencia</a></li>
                                <li><a href="{% url 'operadores:auditoria' %}">Ver Auditoria de Operadores</a></li>
                            {% else %}
                                <li><a href="{% url 'operadores:auditoria_propia' user_id=request.user.id %}">Ver Mis Acciones</a></li>
                            {% endif %}

                            {% if perms.operadores.subcomites %}
                                <li><a href="{% url 'operadores:crear_subcomite'  %}">Crear Subcomite</a></li>
                                <li><a href="{% url 'operadores:listar_subcomites'  %}">Ver Listado de SubComites</a></li>
                            {% endif %}                      
                            
                            {% if perms.operadores.reportes %}
                                <li><a href="{% url 'operadores:csv_operadores'  %}">Descargar Operadores</a></li>
                                <hr>
                            {% endif %}

                            {% if request.user.is_superuser %}
                                <hr>
                                <li><a href="{% url 'admin:index' %}">Administrador</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="col-md-4">
                        {% include 'info_user.html' %}
                    </div>
                </div>
            </div>
        </section>
    </section>
{% endblock %}